# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kellekai/WORK/FTI/VPR-HEAT2D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kellekai/WORK/FTI/VPR-HEAT2D/fti

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kellekai/WORK/FTI/VPR-HEAT2D/fti/CMakeFiles /home/kellekai/WORK/FTI/VPR-HEAT2D/fti/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kellekai/WORK/FTI/VPR-HEAT2D/fti/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named heat

# Build rule for target.
heat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heat
.PHONY : heat

# fast build rule for target.
heat/fast:
	$(MAKE) -f CMakeFiles/heat.dir/build.make CMakeFiles/heat.dir/build
.PHONY : heat/fast

#=============================================================================
# Target rules for targets named gen-cfg

# Build rule for target.
gen-cfg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen-cfg
.PHONY : gen-cfg

# fast build rule for target.
gen-cfg/fast:
	$(MAKE) -f CMakeFiles/gen-cfg.dir/build.make CMakeFiles/gen-cfg.dir/build
.PHONY : gen-cfg/fast

gen-cfg.o: gen-cfg.cpp.o

.PHONY : gen-cfg.o

# target to build an object file
gen-cfg.cpp.o:
	$(MAKE) -f CMakeFiles/gen-cfg.dir/build.make CMakeFiles/gen-cfg.dir/gen-cfg.cpp.o
.PHONY : gen-cfg.cpp.o

gen-cfg.i: gen-cfg.cpp.i

.PHONY : gen-cfg.i

# target to preprocess a source file
gen-cfg.cpp.i:
	$(MAKE) -f CMakeFiles/gen-cfg.dir/build.make CMakeFiles/gen-cfg.dir/gen-cfg.cpp.i
.PHONY : gen-cfg.cpp.i

gen-cfg.s: gen-cfg.cpp.s

.PHONY : gen-cfg.s

# target to generate assembly for a file
gen-cfg.cpp.s:
	$(MAKE) -f CMakeFiles/gen-cfg.dir/build.make CMakeFiles/gen-cfg.dir/gen-cfg.cpp.s
.PHONY : gen-cfg.cpp.s

heatdis-vpr.o: heatdis-vpr.c.o

.PHONY : heatdis-vpr.o

# target to build an object file
heatdis-vpr.c.o:
	$(MAKE) -f CMakeFiles/heat.dir/build.make CMakeFiles/heat.dir/heatdis-vpr.c.o
.PHONY : heatdis-vpr.c.o

heatdis-vpr.i: heatdis-vpr.c.i

.PHONY : heatdis-vpr.i

# target to preprocess a source file
heatdis-vpr.c.i:
	$(MAKE) -f CMakeFiles/heat.dir/build.make CMakeFiles/heat.dir/heatdis-vpr.c.i
.PHONY : heatdis-vpr.c.i

heatdis-vpr.s: heatdis-vpr.c.s

.PHONY : heatdis-vpr.s

# target to generate assembly for a file
heatdis-vpr.c.s:
	$(MAKE) -f CMakeFiles/heat.dir/build.make CMakeFiles/heat.dir/heatdis-vpr.c.s
.PHONY : heatdis-vpr.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... heat"
	@echo "... edit_cache"
	@echo "... gen-cfg"
	@echo "... gen-cfg.o"
	@echo "... gen-cfg.i"
	@echo "... gen-cfg.s"
	@echo "... heatdis-vpr.o"
	@echo "... heatdis-vpr.i"
	@echo "... heatdis-vpr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

