# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kellekai/WORK/FTI/RELEASE-1.4/FEATURE/hdf5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kellekai/WORK/FTI/RELEASE-1.4/FEATURE/hdf5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kellekai/WORK/FTI/RELEASE-1.4/FEATURE/hdf5/CMakeFiles /home/kellekai/WORK/FTI/RELEASE-1.4/FEATURE/hdf5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kellekai/WORK/FTI/RELEASE-1.4/FEATURE/hdf5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fti.shared

# Build rule for target.
fti.shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fti.shared
.PHONY : fti.shared

# fast build rule for target.
fti.shared/fast:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/build
.PHONY : fti.shared/fast

#=============================================================================
# Target rules for targets named fti.static

# Build rule for target.
fti.static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fti.static
.PHONY : fti.static

# fast build rule for target.
fti.static/fast:
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/build
.PHONY : fti.static/fast

#=============================================================================
# Target rules for targets named iniparser

# Build rule for target.
iniparser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iniparser
.PHONY : iniparser

# fast build rule for target.
iniparser/fast:
	$(MAKE) -f deps/iniparser/CMakeFiles/iniparser.dir/build.make deps/iniparser/CMakeFiles/iniparser.dir/build
.PHONY : iniparser/fast

#=============================================================================
# Target rules for targets named jerasure

# Build rule for target.
jerasure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jerasure
.PHONY : jerasure

# fast build rule for target.
jerasure/fast:
	$(MAKE) -f deps/jerasure/CMakeFiles/jerasure.dir/build.make deps/jerasure/CMakeFiles/jerasure.dir/build
.PHONY : jerasure/fast

#=============================================================================
# Target rules for targets named hd2.exe

# Build rule for target.
hd2.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hd2.exe
.PHONY : hd2.exe

# fast build rule for target.
hd2.exe/fast:
	$(MAKE) -f examples/CMakeFiles/hd2.exe.dir/build.make examples/CMakeFiles/hd2.exe.dir/build
.PHONY : hd2.exe/fast

#=============================================================================
# Target rules for targets named hd.exe

# Build rule for target.
hd.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hd.exe
.PHONY : hd.exe

# fast build rule for target.
hd.exe/fast:
	$(MAKE) -f examples/CMakeFiles/hd.exe.dir/build.make examples/CMakeFiles/hd.exe.dir/build
.PHONY : hd.exe/fast

#=============================================================================
# Target rules for targets named init

# Build rule for target.
init: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 init
.PHONY : init

# fast build rule for target.
init/fast:
	$(MAKE) -f examples/CMakeFiles/init.dir/build.make examples/CMakeFiles/init.dir/build
.PHONY : init/fast

#=============================================================================
# Target rules for targets named runall

# Build rule for target.
runall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runall
.PHONY : runall

# fast build rule for target.
runall/fast:
	$(MAKE) -f examples/CMakeFiles/runall.dir/build.make examples/CMakeFiles/runall.dir/build
.PHONY : runall/fast

#=============================================================================
# Target rules for targets named hd

# Build rule for target.
hd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hd
.PHONY : hd

# fast build rule for target.
hd/fast:
	$(MAKE) -f examples/CMakeFiles/hd.dir/build.make examples/CMakeFiles/hd.dir/build
.PHONY : hd/fast

#=============================================================================
# Target rules for targets named hdf

# Build rule for target.
hdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hdf
.PHONY : hdf

# fast build rule for target.
hdf/fast:
	$(MAKE) -f examples/CMakeFiles/hdf.dir/build.make examples/CMakeFiles/hdf.dir/build
.PHONY : hdf/fast

#=============================================================================
# Target rules for targets named hd2

# Build rule for target.
hd2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hd2
.PHONY : hd2

# fast build rule for target.
hd2/fast:
	$(MAKE) -f examples/CMakeFiles/hd2.dir/build.make examples/CMakeFiles/hd2.dir/build
.PHONY : hd2/fast

#=============================================================================
# Target rules for targets named diffSizes

# Build rule for target.
diffSizes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 diffSizes
.PHONY : diffSizes

# fast build rule for target.
diffSizes/fast:
	$(MAKE) -f test/CMakeFiles/diffSizes.dir/build.make test/CMakeFiles/diffSizes.dir/build
.PHONY : diffSizes/fast

#=============================================================================
# Target rules for targets named addInArray

# Build rule for target.
addInArray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 addInArray
.PHONY : addInArray

# fast build rule for target.
addInArray/fast:
	$(MAKE) -f test/CMakeFiles/addInArray.dir/build.make test/CMakeFiles/addInArray.dir/build
.PHONY : addInArray/fast

#=============================================================================
# Target rules for targets named corrupt

# Build rule for target.
corrupt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 corrupt
.PHONY : corrupt

# fast build rule for target.
corrupt/fast:
	$(MAKE) -f test/CMakeFiles/corrupt.dir/build.make test/CMakeFiles/corrupt.dir/build
.PHONY : corrupt/fast

#=============================================================================
# Target rules for targets named syncIntv

# Build rule for target.
syncIntv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 syncIntv
.PHONY : syncIntv

# fast build rule for target.
syncIntv/fast:
	$(MAKE) -f test/CMakeFiles/syncIntv.dir/build.make test/CMakeFiles/syncIntv.dir/build
.PHONY : syncIntv/fast

#=============================================================================
# Target rules for targets named heatdis

# Build rule for target.
heatdis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heatdis
.PHONY : heatdis

# fast build rule for target.
heatdis/fast:
	$(MAKE) -f test/CMakeFiles/heatdis.dir/build.make test/CMakeFiles/heatdis.dir/build
.PHONY : heatdis/fast

#=============================================================================
# Target rules for targets named nodeFlag

# Build rule for target.
nodeFlag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nodeFlag
.PHONY : nodeFlag

# fast build rule for target.
nodeFlag/fast:
	$(MAKE) -f test/CMakeFiles/nodeFlag.dir/build.make test/CMakeFiles/nodeFlag.dir/build
.PHONY : nodeFlag/fast

#=============================================================================
# Target rules for targets named check.exe

# Build rule for target.
check.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check.exe
.PHONY : check.exe

# fast build rule for target.
check.exe/fast:
	$(MAKE) -f test/local/CMakeFiles/check.exe.dir/build.make test/local/CMakeFiles/check.exe.dir/build
.PHONY : check.exe/fast

#=============================================================================
# Target rules for targets named recoverVar.exe

# Build rule for target.
recoverVar.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 recoverVar.exe
.PHONY : recoverVar.exe

# fast build rule for target.
recoverVar.exe/fast:
	$(MAKE) -f test/local/recoverVar/CMakeFiles/recoverVar.exe.dir/build.make test/local/recoverVar/CMakeFiles/recoverVar.exe.dir/build
.PHONY : recoverVar.exe/fast

#=============================================================================
# Target rules for targets named recoverName.exe

# Build rule for target.
recoverName.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 recoverName.exe
.PHONY : recoverName.exe

# fast build rule for target.
recoverName.exe/fast:
	$(MAKE) -f test/local/recoverName/CMakeFiles/recoverName.exe.dir/build.make test/local/recoverName/CMakeFiles/recoverName.exe.dir/build
.PHONY : recoverName.exe/fast

#=============================================================================
# Target rules for targets named checkDCPPosix.exe

# Build rule for target.
checkDCPPosix.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 checkDCPPosix.exe
.PHONY : checkDCPPosix.exe

# fast build rule for target.
checkDCPPosix.exe/fast:
	$(MAKE) -f test/local/diffckpt/CMakeFiles/checkDCPPosix.exe.dir/build.make test/local/diffckpt/CMakeFiles/checkDCPPosix.exe.dir/build
.PHONY : checkDCPPosix.exe/fast

#=============================================================================
# Target rules for targets named consistency

# Build rule for target.
consistency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 consistency
.PHONY : consistency

# fast build rule for target.
consistency/fast:
	$(MAKE) -f test/cornerCases/CMakeFiles/consistency.dir/build.make test/cornerCases/CMakeFiles/consistency.dir/build
.PHONY : consistency/fast

#=============================================================================
# Target rules for targets named ckptHierarchy

# Build rule for target.
ckptHierarchy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ckptHierarchy
.PHONY : ckptHierarchy

# fast build rule for target.
ckptHierarchy/fast:
	$(MAKE) -f test/ckptHierarchy/CMakeFiles/ckptHierarchy.dir/build.make test/ckptHierarchy/CMakeFiles/ckptHierarchy.dir/build
.PHONY : ckptHierarchy/fast

src/IO/cuda-md5/md5Opt.o: src/IO/cuda-md5/md5Opt.c.o

.PHONY : src/IO/cuda-md5/md5Opt.o

# target to build an object file
src/IO/cuda-md5/md5Opt.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/cuda-md5/md5Opt.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/cuda-md5/md5Opt.c.o
.PHONY : src/IO/cuda-md5/md5Opt.c.o

src/IO/cuda-md5/md5Opt.i: src/IO/cuda-md5/md5Opt.c.i

.PHONY : src/IO/cuda-md5/md5Opt.i

# target to preprocess a source file
src/IO/cuda-md5/md5Opt.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/cuda-md5/md5Opt.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/cuda-md5/md5Opt.c.i
.PHONY : src/IO/cuda-md5/md5Opt.c.i

src/IO/cuda-md5/md5Opt.s: src/IO/cuda-md5/md5Opt.c.s

.PHONY : src/IO/cuda-md5/md5Opt.s

# target to generate assembly for a file
src/IO/cuda-md5/md5Opt.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/cuda-md5/md5Opt.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/cuda-md5/md5Opt.c.s
.PHONY : src/IO/cuda-md5/md5Opt.c.s

src/IO/ftiff-dcp.o: src/IO/ftiff-dcp.c.o

.PHONY : src/IO/ftiff-dcp.o

# target to build an object file
src/IO/ftiff-dcp.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/ftiff-dcp.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/ftiff-dcp.c.o
.PHONY : src/IO/ftiff-dcp.c.o

src/IO/ftiff-dcp.i: src/IO/ftiff-dcp.c.i

.PHONY : src/IO/ftiff-dcp.i

# target to preprocess a source file
src/IO/ftiff-dcp.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/ftiff-dcp.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/ftiff-dcp.c.i
.PHONY : src/IO/ftiff-dcp.c.i

src/IO/ftiff-dcp.s: src/IO/ftiff-dcp.c.s

.PHONY : src/IO/ftiff-dcp.s

# target to generate assembly for a file
src/IO/ftiff-dcp.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/ftiff-dcp.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/ftiff-dcp.c.s
.PHONY : src/IO/ftiff-dcp.c.s

src/IO/ftiff.o: src/IO/ftiff.c.o

.PHONY : src/IO/ftiff.o

# target to build an object file
src/IO/ftiff.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/ftiff.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/ftiff.c.o
.PHONY : src/IO/ftiff.c.o

src/IO/ftiff.i: src/IO/ftiff.c.i

.PHONY : src/IO/ftiff.i

# target to preprocess a source file
src/IO/ftiff.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/ftiff.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/ftiff.c.i
.PHONY : src/IO/ftiff.c.i

src/IO/ftiff.s: src/IO/ftiff.c.s

.PHONY : src/IO/ftiff.s

# target to generate assembly for a file
src/IO/ftiff.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/ftiff.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/ftiff.c.s
.PHONY : src/IO/ftiff.c.s

src/IO/hdf5-fti.o: src/IO/hdf5-fti.c.o

.PHONY : src/IO/hdf5-fti.o

# target to build an object file
src/IO/hdf5-fti.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/hdf5-fti.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/hdf5-fti.c.o
.PHONY : src/IO/hdf5-fti.c.o

src/IO/hdf5-fti.i: src/IO/hdf5-fti.c.i

.PHONY : src/IO/hdf5-fti.i

# target to preprocess a source file
src/IO/hdf5-fti.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/hdf5-fti.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/hdf5-fti.c.i
.PHONY : src/IO/hdf5-fti.c.i

src/IO/hdf5-fti.s: src/IO/hdf5-fti.c.s

.PHONY : src/IO/hdf5-fti.s

# target to generate assembly for a file
src/IO/hdf5-fti.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/hdf5-fti.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/hdf5-fti.c.s
.PHONY : src/IO/hdf5-fti.c.s

src/IO/mpio.o: src/IO/mpio.c.o

.PHONY : src/IO/mpio.o

# target to build an object file
src/IO/mpio.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/mpio.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/mpio.c.o
.PHONY : src/IO/mpio.c.o

src/IO/mpio.i: src/IO/mpio.c.i

.PHONY : src/IO/mpio.i

# target to preprocess a source file
src/IO/mpio.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/mpio.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/mpio.c.i
.PHONY : src/IO/mpio.c.i

src/IO/mpio.s: src/IO/mpio.c.s

.PHONY : src/IO/mpio.s

# target to generate assembly for a file
src/IO/mpio.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/mpio.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/mpio.c.s
.PHONY : src/IO/mpio.c.s

src/IO/posix-dcp.o: src/IO/posix-dcp.c.o

.PHONY : src/IO/posix-dcp.o

# target to build an object file
src/IO/posix-dcp.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/posix-dcp.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/posix-dcp.c.o
.PHONY : src/IO/posix-dcp.c.o

src/IO/posix-dcp.i: src/IO/posix-dcp.c.i

.PHONY : src/IO/posix-dcp.i

# target to preprocess a source file
src/IO/posix-dcp.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/posix-dcp.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/posix-dcp.c.i
.PHONY : src/IO/posix-dcp.c.i

src/IO/posix-dcp.s: src/IO/posix-dcp.c.s

.PHONY : src/IO/posix-dcp.s

# target to generate assembly for a file
src/IO/posix-dcp.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/posix-dcp.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/posix-dcp.c.s
.PHONY : src/IO/posix-dcp.c.s

src/IO/posix.o: src/IO/posix.c.o

.PHONY : src/IO/posix.o

# target to build an object file
src/IO/posix.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/posix.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/posix.c.o
.PHONY : src/IO/posix.c.o

src/IO/posix.i: src/IO/posix.c.i

.PHONY : src/IO/posix.i

# target to preprocess a source file
src/IO/posix.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/posix.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/posix.c.i
.PHONY : src/IO/posix.c.i

src/IO/posix.s: src/IO/posix.c.s

.PHONY : src/IO/posix.s

# target to generate assembly for a file
src/IO/posix.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/IO/posix.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/IO/posix.c.s
.PHONY : src/IO/posix.c.s

src/api-cuda.o: src/api-cuda.c.o

.PHONY : src/api-cuda.o

# target to build an object file
src/api-cuda.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/api-cuda.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/api-cuda.c.o
.PHONY : src/api-cuda.c.o

src/api-cuda.i: src/api-cuda.c.i

.PHONY : src/api-cuda.i

# target to preprocess a source file
src/api-cuda.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/api-cuda.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/api-cuda.c.i
.PHONY : src/api-cuda.c.i

src/api-cuda.s: src/api-cuda.c.s

.PHONY : src/api-cuda.s

# target to generate assembly for a file
src/api-cuda.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/api-cuda.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/api-cuda.c.s
.PHONY : src/api-cuda.c.s

src/api.o: src/api.c.o

.PHONY : src/api.o

# target to build an object file
src/api.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/api.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/api.c.o
.PHONY : src/api.c.o

src/api.i: src/api.c.i

.PHONY : src/api.i

# target to preprocess a source file
src/api.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/api.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/api.c.i
.PHONY : src/api.c.i

src/api.s: src/api.c.s

.PHONY : src/api.s

# target to generate assembly for a file
src/api.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/api.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/api.c.s
.PHONY : src/api.c.s

src/checkpoint.o: src/checkpoint.c.o

.PHONY : src/checkpoint.o

# target to build an object file
src/checkpoint.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/checkpoint.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/checkpoint.c.o
.PHONY : src/checkpoint.c.o

src/checkpoint.i: src/checkpoint.c.i

.PHONY : src/checkpoint.i

# target to preprocess a source file
src/checkpoint.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/checkpoint.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/checkpoint.c.i
.PHONY : src/checkpoint.c.i

src/checkpoint.s: src/checkpoint.c.s

.PHONY : src/checkpoint.s

# target to generate assembly for a file
src/checkpoint.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/checkpoint.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/checkpoint.c.s
.PHONY : src/checkpoint.c.s

src/conf.o: src/conf.c.o

.PHONY : src/conf.o

# target to build an object file
src/conf.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/conf.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/conf.c.o
.PHONY : src/conf.c.o

src/conf.i: src/conf.c.i

.PHONY : src/conf.i

# target to preprocess a source file
src/conf.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/conf.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/conf.c.i
.PHONY : src/conf.c.i

src/conf.s: src/conf.c.s

.PHONY : src/conf.s

# target to generate assembly for a file
src/conf.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/conf.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/conf.c.s
.PHONY : src/conf.c.s

src/dcp.o: src/dcp.c.o

.PHONY : src/dcp.o

# target to build an object file
src/dcp.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/dcp.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/dcp.c.o
.PHONY : src/dcp.c.o

src/dcp.i: src/dcp.c.i

.PHONY : src/dcp.i

# target to preprocess a source file
src/dcp.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/dcp.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/dcp.c.i
.PHONY : src/dcp.c.i

src/dcp.s: src/dcp.c.s

.PHONY : src/dcp.s

# target to generate assembly for a file
src/dcp.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/dcp.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/dcp.c.s
.PHONY : src/dcp.c.s

src/fortran/ftif.o: src/fortran/ftif.c.o

.PHONY : src/fortran/ftif.o

# target to build an object file
src/fortran/ftif.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/fortran/ftif.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/fortran/ftif.c.o
.PHONY : src/fortran/ftif.c.o

src/fortran/ftif.i: src/fortran/ftif.c.i

.PHONY : src/fortran/ftif.i

# target to preprocess a source file
src/fortran/ftif.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/fortran/ftif.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/fortran/ftif.c.i
.PHONY : src/fortran/ftif.c.i

src/fortran/ftif.s: src/fortran/ftif.c.s

.PHONY : src/fortran/ftif.s

# target to generate assembly for a file
src/fortran/ftif.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/fortran/ftif.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/fortran/ftif.c.s
.PHONY : src/fortran/ftif.c.s

src/fti-io.o: src/fti-io.c.o

.PHONY : src/fti-io.o

# target to build an object file
src/fti-io.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/fti-io.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/fti-io.c.o
.PHONY : src/fti-io.c.o

src/fti-io.i: src/fti-io.c.i

.PHONY : src/fti-io.i

# target to preprocess a source file
src/fti-io.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/fti-io.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/fti-io.c.i
.PHONY : src/fti-io.c.i

src/fti-io.s: src/fti-io.c.s

.PHONY : src/fti-io.s

# target to generate assembly for a file
src/fti-io.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/fti-io.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/fti-io.c.s
.PHONY : src/fti-io.c.s

src/icp.o: src/icp.c.o

.PHONY : src/icp.o

# target to build an object file
src/icp.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/icp.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/icp.c.o
.PHONY : src/icp.c.o

src/icp.i: src/icp.c.i

.PHONY : src/icp.i

# target to preprocess a source file
src/icp.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/icp.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/icp.c.i
.PHONY : src/icp.c.i

src/icp.s: src/icp.c.s

.PHONY : src/icp.s

# target to generate assembly for a file
src/icp.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/icp.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/icp.c.s
.PHONY : src/icp.c.s

src/meta.o: src/meta.c.o

.PHONY : src/meta.o

# target to build an object file
src/meta.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/meta.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/meta.c.o
.PHONY : src/meta.c.o

src/meta.i: src/meta.c.i

.PHONY : src/meta.i

# target to preprocess a source file
src/meta.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/meta.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/meta.c.i
.PHONY : src/meta.c.i

src/meta.s: src/meta.c.s

.PHONY : src/meta.s

# target to generate assembly for a file
src/meta.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/meta.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/meta.c.s
.PHONY : src/meta.c.s

src/postckpt.o: src/postckpt.c.o

.PHONY : src/postckpt.o

# target to build an object file
src/postckpt.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/postckpt.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/postckpt.c.o
.PHONY : src/postckpt.c.o

src/postckpt.i: src/postckpt.c.i

.PHONY : src/postckpt.i

# target to preprocess a source file
src/postckpt.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/postckpt.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/postckpt.c.i
.PHONY : src/postckpt.c.i

src/postckpt.s: src/postckpt.c.s

.PHONY : src/postckpt.s

# target to generate assembly for a file
src/postckpt.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/postckpt.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/postckpt.c.s
.PHONY : src/postckpt.c.s

src/postreco.o: src/postreco.c.o

.PHONY : src/postreco.o

# target to build an object file
src/postreco.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/postreco.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/postreco.c.o
.PHONY : src/postreco.c.o

src/postreco.i: src/postreco.c.i

.PHONY : src/postreco.i

# target to preprocess a source file
src/postreco.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/postreco.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/postreco.c.i
.PHONY : src/postreco.c.i

src/postreco.s: src/postreco.c.s

.PHONY : src/postreco.s

# target to generate assembly for a file
src/postreco.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/postreco.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/postreco.c.s
.PHONY : src/postreco.c.s

src/recover.o: src/recover.c.o

.PHONY : src/recover.o

# target to build an object file
src/recover.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/recover.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/recover.c.o
.PHONY : src/recover.c.o

src/recover.i: src/recover.c.i

.PHONY : src/recover.i

# target to preprocess a source file
src/recover.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/recover.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/recover.c.i
.PHONY : src/recover.c.i

src/recover.s: src/recover.c.s

.PHONY : src/recover.s

# target to generate assembly for a file
src/recover.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/recover.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/recover.c.s
.PHONY : src/recover.c.s

src/stage.o: src/stage.c.o

.PHONY : src/stage.o

# target to build an object file
src/stage.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/stage.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/stage.c.o
.PHONY : src/stage.c.o

src/stage.i: src/stage.c.i

.PHONY : src/stage.i

# target to preprocess a source file
src/stage.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/stage.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/stage.c.i
.PHONY : src/stage.c.i

src/stage.s: src/stage.c.s

.PHONY : src/stage.s

# target to generate assembly for a file
src/stage.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/stage.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/stage.c.s
.PHONY : src/stage.c.s

src/topo.o: src/topo.c.o

.PHONY : src/topo.o

# target to build an object file
src/topo.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/topo.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/topo.c.o
.PHONY : src/topo.c.o

src/topo.i: src/topo.c.i

.PHONY : src/topo.i

# target to preprocess a source file
src/topo.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/topo.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/topo.c.i
.PHONY : src/topo.c.i

src/topo.s: src/topo.c.s

.PHONY : src/topo.s

# target to generate assembly for a file
src/topo.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/topo.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/topo.c.s
.PHONY : src/topo.c.s

src/util/dataset.o: src/util/dataset.c.o

.PHONY : src/util/dataset.o

# target to build an object file
src/util/dataset.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/dataset.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/dataset.c.o
.PHONY : src/util/dataset.c.o

src/util/dataset.i: src/util/dataset.c.i

.PHONY : src/util/dataset.i

# target to preprocess a source file
src/util/dataset.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/dataset.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/dataset.c.i
.PHONY : src/util/dataset.c.i

src/util/dataset.s: src/util/dataset.c.s

.PHONY : src/util/dataset.s

# target to generate assembly for a file
src/util/dataset.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/dataset.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/dataset.c.s
.PHONY : src/util/dataset.c.s

src/util/failure-injection.o: src/util/failure-injection.c.o

.PHONY : src/util/failure-injection.o

# target to build an object file
src/util/failure-injection.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/failure-injection.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/failure-injection.c.o
.PHONY : src/util/failure-injection.c.o

src/util/failure-injection.i: src/util/failure-injection.c.i

.PHONY : src/util/failure-injection.i

# target to preprocess a source file
src/util/failure-injection.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/failure-injection.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/failure-injection.c.i
.PHONY : src/util/failure-injection.c.i

src/util/failure-injection.s: src/util/failure-injection.c.s

.PHONY : src/util/failure-injection.s

# target to generate assembly for a file
src/util/failure-injection.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/failure-injection.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/failure-injection.c.s
.PHONY : src/util/failure-injection.c.s

src/util/ini.o: src/util/ini.c.o

.PHONY : src/util/ini.o

# target to build an object file
src/util/ini.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/ini.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/ini.c.o
.PHONY : src/util/ini.c.o

src/util/ini.i: src/util/ini.c.i

.PHONY : src/util/ini.i

# target to preprocess a source file
src/util/ini.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/ini.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/ini.c.i
.PHONY : src/util/ini.c.i

src/util/ini.s: src/util/ini.c.s

.PHONY : src/util/ini.s

# target to generate assembly for a file
src/util/ini.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/ini.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/ini.c.s
.PHONY : src/util/ini.c.s

src/util/keymap.o: src/util/keymap.c.o

.PHONY : src/util/keymap.o

# target to build an object file
src/util/keymap.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/keymap.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/keymap.c.o
.PHONY : src/util/keymap.c.o

src/util/keymap.i: src/util/keymap.c.i

.PHONY : src/util/keymap.i

# target to preprocess a source file
src/util/keymap.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/keymap.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/keymap.c.i
.PHONY : src/util/keymap.c.i

src/util/keymap.s: src/util/keymap.c.s

.PHONY : src/util/keymap.s

# target to generate assembly for a file
src/util/keymap.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/keymap.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/keymap.c.s
.PHONY : src/util/keymap.c.s

src/util/macros.o: src/util/macros.c.o

.PHONY : src/util/macros.o

# target to build an object file
src/util/macros.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/macros.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/macros.c.o
.PHONY : src/util/macros.c.o

src/util/macros.i: src/util/macros.c.i

.PHONY : src/util/macros.i

# target to preprocess a source file
src/util/macros.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/macros.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/macros.c.i
.PHONY : src/util/macros.c.i

src/util/macros.s: src/util/macros.c.s

.PHONY : src/util/macros.s

# target to generate assembly for a file
src/util/macros.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/macros.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/macros.c.s
.PHONY : src/util/macros.c.s

src/util/metaqueue.o: src/util/metaqueue.c.o

.PHONY : src/util/metaqueue.o

# target to build an object file
src/util/metaqueue.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/metaqueue.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/metaqueue.c.o
.PHONY : src/util/metaqueue.c.o

src/util/metaqueue.i: src/util/metaqueue.c.i

.PHONY : src/util/metaqueue.i

# target to preprocess a source file
src/util/metaqueue.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/metaqueue.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/metaqueue.c.i
.PHONY : src/util/metaqueue.c.i

src/util/metaqueue.s: src/util/metaqueue.c.s

.PHONY : src/util/metaqueue.s

# target to generate assembly for a file
src/util/metaqueue.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/metaqueue.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/metaqueue.c.s
.PHONY : src/util/metaqueue.c.s

src/util/tools.o: src/util/tools.c.o

.PHONY : src/util/tools.o

# target to build an object file
src/util/tools.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/tools.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/tools.c.o
.PHONY : src/util/tools.c.o

src/util/tools.i: src/util/tools.c.i

.PHONY : src/util/tools.i

# target to preprocess a source file
src/util/tools.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/tools.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/tools.c.i
.PHONY : src/util/tools.c.i

src/util/tools.s: src/util/tools.c.s

.PHONY : src/util/tools.s

# target to generate assembly for a file
src/util/tools.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/tools.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/tools.c.s
.PHONY : src/util/tools.c.s

src/util/utility.o: src/util/utility.c.o

.PHONY : src/util/utility.o

# target to build an object file
src/util/utility.c.o:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/utility.c.o
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/utility.c.o
.PHONY : src/util/utility.c.o

src/util/utility.i: src/util/utility.c.i

.PHONY : src/util/utility.i

# target to preprocess a source file
src/util/utility.c.i:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/utility.c.i
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/utility.c.i
.PHONY : src/util/utility.c.i

src/util/utility.s: src/util/utility.c.s

.PHONY : src/util/utility.s

# target to generate assembly for a file
src/util/utility.c.s:
	$(MAKE) -f CMakeFiles/fti.shared.dir/build.make CMakeFiles/fti.shared.dir/src/util/utility.c.s
	$(MAKE) -f CMakeFiles/fti.static.dir/build.make CMakeFiles/fti.static.dir/src/util/utility.c.s
.PHONY : src/util/utility.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... fti.shared"
	@echo "... install"
	@echo "... fti.static"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... iniparser"
	@echo "... jerasure"
	@echo "... hd2.exe"
	@echo "... hd.exe"
	@echo "... init"
	@echo "... runall"
	@echo "... hd"
	@echo "... hdf"
	@echo "... hd2"
	@echo "... diffSizes"
	@echo "... addInArray"
	@echo "... corrupt"
	@echo "... syncIntv"
	@echo "... heatdis"
	@echo "... nodeFlag"
	@echo "... check.exe"
	@echo "... recoverVar.exe"
	@echo "... recoverName.exe"
	@echo "... checkDCPPosix.exe"
	@echo "... consistency"
	@echo "... ckptHierarchy"
	@echo "... src/IO/cuda-md5/md5Opt.o"
	@echo "... src/IO/cuda-md5/md5Opt.i"
	@echo "... src/IO/cuda-md5/md5Opt.s"
	@echo "... src/IO/ftiff-dcp.o"
	@echo "... src/IO/ftiff-dcp.i"
	@echo "... src/IO/ftiff-dcp.s"
	@echo "... src/IO/ftiff.o"
	@echo "... src/IO/ftiff.i"
	@echo "... src/IO/ftiff.s"
	@echo "... src/IO/hdf5-fti.o"
	@echo "... src/IO/hdf5-fti.i"
	@echo "... src/IO/hdf5-fti.s"
	@echo "... src/IO/mpio.o"
	@echo "... src/IO/mpio.i"
	@echo "... src/IO/mpio.s"
	@echo "... src/IO/posix-dcp.o"
	@echo "... src/IO/posix-dcp.i"
	@echo "... src/IO/posix-dcp.s"
	@echo "... src/IO/posix.o"
	@echo "... src/IO/posix.i"
	@echo "... src/IO/posix.s"
	@echo "... src/api-cuda.o"
	@echo "... src/api-cuda.i"
	@echo "... src/api-cuda.s"
	@echo "... src/api.o"
	@echo "... src/api.i"
	@echo "... src/api.s"
	@echo "... src/checkpoint.o"
	@echo "... src/checkpoint.i"
	@echo "... src/checkpoint.s"
	@echo "... src/conf.o"
	@echo "... src/conf.i"
	@echo "... src/conf.s"
	@echo "... src/dcp.o"
	@echo "... src/dcp.i"
	@echo "... src/dcp.s"
	@echo "... src/fortran/ftif.o"
	@echo "... src/fortran/ftif.i"
	@echo "... src/fortran/ftif.s"
	@echo "... src/fti-io.o"
	@echo "... src/fti-io.i"
	@echo "... src/fti-io.s"
	@echo "... src/icp.o"
	@echo "... src/icp.i"
	@echo "... src/icp.s"
	@echo "... src/meta.o"
	@echo "... src/meta.i"
	@echo "... src/meta.s"
	@echo "... src/postckpt.o"
	@echo "... src/postckpt.i"
	@echo "... src/postckpt.s"
	@echo "... src/postreco.o"
	@echo "... src/postreco.i"
	@echo "... src/postreco.s"
	@echo "... src/recover.o"
	@echo "... src/recover.i"
	@echo "... src/recover.s"
	@echo "... src/stage.o"
	@echo "... src/stage.i"
	@echo "... src/stage.s"
	@echo "... src/topo.o"
	@echo "... src/topo.i"
	@echo "... src/topo.s"
	@echo "... src/util/dataset.o"
	@echo "... src/util/dataset.i"
	@echo "... src/util/dataset.s"
	@echo "... src/util/failure-injection.o"
	@echo "... src/util/failure-injection.i"
	@echo "... src/util/failure-injection.s"
	@echo "... src/util/ini.o"
	@echo "... src/util/ini.i"
	@echo "... src/util/ini.s"
	@echo "... src/util/keymap.o"
	@echo "... src/util/keymap.i"
	@echo "... src/util/keymap.s"
	@echo "... src/util/macros.o"
	@echo "... src/util/macros.i"
	@echo "... src/util/macros.s"
	@echo "... src/util/metaqueue.o"
	@echo "... src/util/metaqueue.i"
	@echo "... src/util/metaqueue.s"
	@echo "... src/util/tools.o"
	@echo "... src/util/tools.i"
	@echo "... src/util/tools.s"
	@echo "... src/util/utility.o"
	@echo "... src/util/utility.i"
	@echo "... src/util/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

