# All types supported by the current Fortran implementation
BPP_FORTTYPES="CHARACTER1 CHARACTER4 COMPLEX4 COMPLEX8 COMPLEX16 INTEGER1 INTEGER2 INTEGER4 INTEGER8 INTEGER16 LOGICAL1 LOGICAL2 LOGICAL4 LOGICAL8 LOGICAL16 REAL4 REAL8 REAL16 "
# for compatibility
FORTTYPES="${BPP_FORTTYPES}"
