PROGRAM CHECK
      USE MPI
      USE FTI
      IMPLICIT NONE

!**** VARIABLE DEFINITIONS
      INTEGER                 :: IERROR
      INTEGER, TARGET         :: FTI_COMM_WORLD
      INTEGER, PARAMETER      :: BUFFER = 256
      INTEGER                 :: CRASH, LEVEL, DIFF_SIZES
      CHARACTER(LEN=BUFFER)   :: CF
      CHARACTER(LEN=1)   :: CRASH_CHAR, LEVEL_CHAR, DIFF_SIZES_CHAR

!**** GET ARGUMENTS FROM COMMAND LINE 
      CALL GETARG(1, CF)
      CALL GETARG(2, CRASH_CHAR)
      CALL GETARG(3, LEVEL_CHAR)
      CALL GETARG(4, DIFF_SIZES_CHAR)
      READ (CRASH_CHAR(1:1),'(I4)') CRASH
      READ (LEVEL_CHAR(1:1),'(I4)') LEVEL
      READ (DIFF_SIZES_CHAR(1:1),'(I4)') DIFF_SIZES

!**** MAIN PROGRAM STARTS HERE
      CALL MPI_INIT(IERROR)
      FTI_COMM_WORLD = MPI_COMM_WORLD
      CALL FTI_INIT(CF, FTI_COMM_WORLD, IERROR)

      PRINT *, "HELLO WORLD!", CF, CRASH, LEVEL, DIFF_SIZES

      CALL FTI_FINALIZE(IERROR)
      CALL MPI_FINALIZE(IERROR)
END PROGRAM

