#!/bin/bash

export MPIRUN_ARGS=--oversubscribe

$(dirname ${BASH_SOURCE[0]})/testdriver --quiet --path-modules "build/testing/itf/modules" -f recovername:standard:iolib=3 -f standard:ckpt_disruption:expected=fail $@
    
retval=$?

unset MPIRUN_ARGS

exit $retval