#!/bin/bash
# Brief:
# A proxy script that calls ITF testdriver contained in the src directory.
#
# This script provides a quick way to invoke ITF test driver.
# It can be modified to support users debugging and launching tests locally.
# For users trying to mimick the Jenkins environment, check ci_testdriver.

export MPIRUN_ARGS=--oversubscribe

@CMAKE_CURRENT_SOURCE_DIR@/testdriver --path-modules "@itf_dir@/modules" $@
    
retval=$?

unset MPIRUN_ARGS

exit $retval