# Generated by CMake 3.5.1

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget fti.static fti.shared fti_f90.static fti_f90.shared)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target fti.static
add_library(fti.static STATIC IMPORTED)

# Create imported target fti.shared
add_library(fti.shared SHARED IMPORTED)

# Create imported target fti_f90.static
add_library(fti_f90.static STATIC IMPORTED)

# Create imported target fti_f90.shared
add_library(fti_f90.shared SHARED IMPORTED)

# Import target "fti.static" for configuration ""
set_property(TARGET fti.static APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(fti.static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "/usr/lib/openmpi/lib/libmpi.so"
  IMPORTED_LOCATION_NOCONFIG "/home/kellekai/Dokumente/BSC/WORK/FTI_REPOS/debug/src/lib/libfti.a"
  )

# Import target "fti.shared" for configuration ""
set_property(TARGET fti.shared APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(fti.shared PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "/usr/lib/openmpi/lib/libmpi.so"
  IMPORTED_LOCATION_NOCONFIG "/home/kellekai/Dokumente/BSC/WORK/FTI_REPOS/debug/src/lib/libfti.so"
  IMPORTED_SONAME_NOCONFIG "libfti.so"
  )

# Import target "fti_f90.static" for configuration ""
set_property(TARGET fti_f90.static APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(fti_f90.static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C;Fortran"
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "fti.static;/usr/lib/openmpi/lib/libmpi_usempif08.so;/usr/lib/openmpi/lib/libmpi_usempi_ignore_tkr.so;/usr/lib/openmpi/lib/libmpi_mpifh.so;/usr/lib/openmpi/lib/libmpi.so;/usr/lib/openmpi/lib/libmpi.so"
  IMPORTED_LOCATION_NOCONFIG "/home/kellekai/Dokumente/BSC/WORK/FTI_REPOS/debug/src/lib/libfti_f90.a"
  )

# Import target "fti_f90.shared" for configuration ""
set_property(TARGET fti_f90.shared APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(fti_f90.shared PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "fti.shared;/usr/lib/openmpi/lib/libmpi_usempif08.so;/usr/lib/openmpi/lib/libmpi_usempi_ignore_tkr.so;/usr/lib/openmpi/lib/libmpi_mpifh.so;/usr/lib/openmpi/lib/libmpi.so;/usr/lib/openmpi/lib/libmpi.so"
  IMPORTED_LOCATION_NOCONFIG "/home/kellekai/Dokumente/BSC/WORK/FTI_REPOS/debug/src/lib/libfti_f90.so"
  IMPORTED_SONAME_NOCONFIG "libfti_f90.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
